### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by brentzundel** [w3c/vc-test-suite#21]
Timeout for tests seems to be set to 2000 ms
generating actual keys for CL signatures may take much much longer than this.
Can the timeout be changed?

**Comment by brentzundel** [comment]
@dmitrizagidulin Do you know if this is possible?

**Comment by dmitrizagidulin** [comment]
@brentzundel Right! So! You have a couple of options. You can override mocha timeouts from the commandline, so you can do something like (assuming you want 10 seconds):

```
npm test -- --timeout 10000
```
(The extra `--` there in the middle is intentional).

The other thing to consider is - is generating fresh keys required for each run? It's fairly common to generate test keys once, and commit them to the test suite, and reuse them (to prevent exactly this issue).

**Comment by brentzundel** [comment]
Thanks for the timeout instructions. That helps a lot.

As far as generating fresh keys for each run, the way our signatures work
requires a key to be generated for each attribute in the credential that is
to be signed. As the test json-ld input files do not all follow the same
schema, my program infers the schema from the input json-ld and generates
the necessary keys for signing.
In the real world, the keys for signing would be generated once per
credential type that will be issued.

**Comment by dmitrizagidulin** [comment]
@brentzundel Sounds like this has been resolved (per your email), feel free to close?

**Comment by brentzundel** [comment]
Could this bit of information also be added to the README?

**Comment by dmitrizagidulin** [comment]
@brentzundel Sure, good idea.

**Comment by dmitrizagidulin** [comment]
Timeout itself has been fixed/addressed, now just need to add comment to the README - @dmitrizagidulin to address today.

**Comment by dmitrizagidulin** [comment]
Fixed in PR #67, closing.
