### ISSUE TITLE
jwt test generator options are applied to the following zkp ones

### ISSUE THREAD

**Issue by kdimak** [w3c/vc-test-suite#98]
As a result, the following flags are passed to a generator for `zkp` tests:
- `--jwt`
- `--jwt-aud`
- `--jwt-presentation`

**Comment by clehner** [comment]
This makes it difficult to test `zkp` and `jwt` in the same run.

It is because the `jwt` tests mutate the options object:
https://github.com/w3c/vc-test-suite/blob/gh-pages/test/vc-data-model-1.0/50-jwt.js#L68

Workaround: disable jwt tests when testing zkp, and vice versa. i.e. test twice with different values for `sectionsNotSupported` in `config.json`: one with `["jwt"]`, and one with `["zkp"]`. Or, ignore `--jwt` flags when the filename contains `example-015-zkp`.
